# Generated by Django 2.2.4 on 2022-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShows_app', '0004_auto_20220620_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='describtion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
