# Generated by Django 2.2.4 on 2022-06-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShows_app', '0005_auto_20220620_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='describtion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
