# Generated by Django 2.2.4 on 2022-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShows_app', '0006_auto_20220620_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='describtion',
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
