# Generated by Django 2.2.4 on 2022-06-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='null'),
        ),
        migrations.DeleteModel(
            name='ninjas',
        ),
    ]
