# Generated by Django 2.2.4 on 2022-06-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_ninjas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ninjas',
        ),
    ]
