# Generated by Django 2.2.4 on 2022-06-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20220617_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(default='default'),
        ),
    ]
