# Generated by Django 2.2.4 on 2022-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_authors_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='books',
        ),
        migrations.RemoveField(
            model_name='books',
            name='desc',
        ),
        migrations.AddField(
            model_name='books',
            name='books',
            field=models.ManyToManyField(related_name='books', to='books_authors_app.Authors'),
        ),
    ]
