# Generated by Django 2.2.4 on 2022-06-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0005_auto_20220617_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='books',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
