# Generated by Django 2.2.4 on 2022-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0007_authors_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='books',
            name='books',
        ),
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='books', to='books_authors_app.Books'),
        ),
    ]
