# Generated by Django 2.2.4 on 2022-06-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0008_auto_20220617_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
