# Generated by Django 2.2.4 on 2022-06-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0010_authors_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
