# Generated by Django 2.2.4 on 2022-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0013_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
