# Generated by Django 2.2.4 on 2022-06-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('liked_books', models.CharField(max_length=255)),
                ('books_uploaded', models.CharField(max_length=255)),
            ],
        ),
    ]
