# Generated by Django 2.2.4 on 2022-06-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='favorite_books_app.User'),
        ),
    ]
