# Generated by Django 2.2.4 on 2022-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0003_book_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='vaf_books', to='favorite_books_app.User'),
        ),
    ]
