# Generated by Django 2.2.4 on 2022-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0008_auto_20220627_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='fav_books', to='favorite_books_app.User'),
        ),
    ]
